In [ ]:
# 본인의 이름, 학번을 작성하여 실행하세요.
print("홍기찬")
print("20222051")

홍기찬
20222051


## 이후 강의 PDF 예제 내용을 작성하여 실행하세요.

In [ ]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [4]:
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [5]:
x  = '"!~$$*&!@'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
symbols = "'~!-$*$k!@"
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[39, 126, 33, 45, 36, 42, 36, 107, 33, 64]


In [7]:
symbols = "'~!-$*$k!@"
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126, 107] 

Map function:
>>> <map object at 0x78b13edfe6e0>
List after map:
>>> [39, 126, 33, 45, 36, 42, 36, 107, 33, 64]


In [1]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)


for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [2]:
symbols = "!#^&d#"

ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 100, 35)


In [3]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
    print(tshirt)

black S
white S
black M
white M
black L
white L


In [4]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [
    ('USA', '31195855'),
    ('BRA', 'CE342567'),
    ('ESP', 'XDA205856'),
    ('BRA', 'CE342567'),
    ('ESP', 'XDA205856'),
    ('USA', '31195855'),
    ('USA', '31195855'),
]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855
USA/31195855
USA/31195855
USA/31195855
USA/31195855
USA/31195855
USA/31195855


In [5]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP
BRA
ESP
USA
USA


In [6]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates

print(latitude)
print(longitude)

33.9425
-118.408056


In [7]:
a = 10
b = 20

b, a = a, b

print(a, b)


20 10


In [8]:
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)


(2, 4)
(2, 4)
2 4


In [9]:
import os

_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')

print(filename)


idrsa.pub


In [10]:
a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)


0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [11]:
a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)


0 [1, 2] 3 4
[0, 1] 2 3 4


In [12]:
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York–Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46)),
]

print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))


                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York–Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [13]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')

tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))

print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])


36.933
(35.689, 139.691)
JP


In [14]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
LatLong = namedtuple('LatLong', 'lat long')

delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)

print(delhi._asdict())

for key, value in delhi._asdict().items():
    print(key + ':', value)


{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [15]:
l = [10, 20, 30, 40, 50, 60]

print(l[:2])
print(l[2:])
print(l[3:])


[10, 20]
[30, 40, 50, 60]
[40, 50, 60]


In [16]:
invoice = """
0.....6..............................25...........33..........40........
1996    Pinomori                       $17.50      2            $52.50
1489    6mm Tactile                    $4.95       2            $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])


           Pinomori         
           6mm Tactile      
 


In [21]:
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


In [22]:
l[2:5] = 100

TypeError: must assign iterable to extended slice

In [23]:
l = list(range(10))
l[2:5] = [100]
print(l)

[0, 1, 100, 5, 6, 7, 8, 9]


In [24]:
l = [1, 2, 3]
print(l * 5)

print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


In [20]:
board = [['-'] * 3 for _ in range(3)]
print(board)

board[1][2] = 'X'
print(board)

[['-', '-', '-'], ['-', '-', '-'], ['-', '-', '-']]
[['-', '-', '-'], ['-', '-', 'X'], ['-', '-', '-']]


In [19]:
weird_board = [['-'] * 3] * 3
print(weird_board)

weird_board[1][2] = '0'
print(weird_board)

[['-', '-', '-'], ['-', '-', '-'], ['-', '-', '-']]
[['-', '-', '0'], ['-', '-', '0'], ['-', '-', '0']]


In [18]:
row = ['-'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'
print(board)

[['-', '-', 'X'], ['-', '-', 'X'], ['-', '-', 'X']]


In [17]:
board = []
for i in range(3):
    row = ['-'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'
print(board)

[['-', '-', '-'], ['-', '-', '-'], ['-', '-', '-']]
[['-', '-', '-'], ['-', '-', '-'], ['X', '-', '-']]


In [25]:
l = [1, 2, 3]
id(l)
l *= 2
l
id(l)


136159612257088

In [26]:
t = (1, 2, 3)
id(t)
t *= 2
id(t)

136159863741824

In [27]:
t = (1, 2, [30, 40])
print(t)
t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [28]:
print(t)

(1, 2, [30, 40, 50, 60])


In [29]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)
fruits
sorted(fruits, reverse=True)
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [30]:
sorted(fruits, key=len, reverse=True)
fruits
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [31]:
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.18854556176724324

In [32]:
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

floats2[-1]

floats == floats2

True

In [33]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)
memv[0]

memv_oct = memv.cast('B')
memv_oct.tolist()

memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [34]:
data = bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])
mv[0] = 72
print(data)

104
bytearray(b'Hello world')


In [35]:
import numpy
a = numpy.arange(12)
a
type(a)

numpy.ndarray

In [36]:
a.shape
a.shape = 3, 4
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a[2]
a[2, 1]
a[:, 1]

array([1, 5, 9])

In [38]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])